#!/usr/bin/lua

local uci = require 'luci.model.uci'
local site = require 'gluon.site_config'
local fs = require "nixio.fs"
local c = uci.cursor()

local currentsite = c:get("currentsite", "current", "name")

local file = "/etc/sysupgrade.conf"
local configured = false

for line in io.lines(file) do
  if line == "/etc/config/currentsite" then
    configured = true
  end
end

if configured == false then
  f = io.open(file,"a")
  f:write("/etc/config/currentsite\n")
  f:close()
end

if site.site_name ~= c:get('siteselect', currentsite, 'sitename') then
  fs.copy(c:get('siteselect', currentsite , 'path'), '/lib/gluon/site.conf')
end
