#!/bin/sh

. /lib/functions.sh

uci_set network client defaultroute '0' 

uci_remove network wan6
uci_add network interface wan6
uci_set network wan6 ifname '@wan'
uci_set network wan6 proto 'dhcpv6'
uci_set network wan6 reqprefix 'no'
